module.exports = {
  'rules': {
    'no-cond-assign': 2,
    'no-console': 2,
    'no-constant-condition': 2,
    'comma-dangle': 0,
    'no-debugger': 2,
    'no-dupe-keys': 2,
    'no-empty': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': 0,
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-negated-in-lhs': 2,
    'no-obj-calls': 2,
    'no-sparse-arrays': 2,
    'no-unreachable': 2,
    'use-isnan': 2,
    'valid-jsdoc': 1,
    'valid-typeof': 2,
    'block-scoped-var': 1,
    'complexity': [1,10],
    'curly': [2, 'all'],
    'dot-notation': 1,
    'eqeqeq': [2, 'smart'],
    'no-alert': 2,
    'no-caller': 2,
    'no-div-regex': 2,
    'no-else-return': 2,
    'no-empty-label': 2,
    'no-eq-null': 0,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-fallthrough': 0,
    'no-floating-decimal': 0,
    'no-implied-eval': 2,
    'no-labels': 2,
    'no-iterator': 2,
    'no-lone-blocks': 2,
    'no-loop-func': 2,
    'no-multi-str': 1,
    'no-native-reassign': 2,
    'no-new': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-compare': 2,
    'no-unused-expressions': 2,
    'no-warning-comments': 0,
    'no-with': 2,
    'yoda': 2,
    'radix': 2,
    'wrap-iife': [2,'outside'],
    'no-global-strict': 0,
    'strict': [2, 'global'],
    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-shadow': 0,
    'no-shadow-restricted-names': 2,
    'no-undef': 2,
    'no-undef-init': 2,
    'no-unused-vars': [2, {'vars': 'local', 'args': 'after-used'}],
    'no-use-before-define': 0,
    'handle-callback-err': 0,
    'no-path-concat': 2,
    'no-process-exit': 0,
    'no-sync': 0,
    'brace-style': [2, '1tbs'],
    'camelcase': 2,
    'consistent-this': [2, 'self'],
    'func-names': 0,
    'func-style': 0,
    'new-cap': 2,
    'new-parens': 2,
    'no-nested-ternary': 2,
    'no-array-constructor': 2,
    'no-new-object': 2,
    'no-spaced-func': 2,
    'semi-spacing': 2,
    'no-ternary': 0,
    'no-underscore-dangle': 0,
    'no-extra-parens': 0,
    'quotes': [2, 'single', 'avoid-escape'],
    'quote-props': 0,
    'semi': [2, 'always'],
    'sort-vars': 2,
    'array-bracket-spacing': [2, 'never'],
    'object-curly-spacing': [1, 'always'],
    'space-infix-ops': 2,
    'space-return-throw-case': 2,
    'space-unary-ops': 2,
    'max-nested-callbacks': [2, 4],
    'one-var': 0,
    'wrap-regex': 2,
    'max-len': [1, 80, 4],
    'no-mixed-requires': 2,
    'consistent-return': 0,
    'space-after-keywords': 2,
  }
};
