module.exports = {
  "rules": {
    "no-alert": 2,
    "no-array-constructor": 2,
    "no-bitwise": 0,
    "no-caller": 2,
    "no-case-declarations": 2,
    "no-catch-shadow": 2,
    "no-cond-assign": 2,
    "no-console": 2,
    "no-constant-condition": 2,
    "no-continue": 0,
    "no-control-regex": 2,
    "no-debugger": 2,
    "no-delete-var": 2,
    "no-div-regex": 2,
    "no-dupe-keys": 2,
    "no-dupe-args": 2,
    "no-duplicate-case": 2,
    "no-else-return": 2,
    "no-empty": 2,
    "no-empty-character-class": 2,
    "no-empty-function": [2, { "allow": ["arrowFunctions"] }],
    "no-empty-pattern": 2,
    "no-eq-null": 0,
    "no-eval": 2,
    "no-ex-assign": 2,
    "no-extend-native": 2,
    "no-extra-bind": 2,
    "no-extra-boolean-cast": 2,
    "no-extra-label": 2,
    "no-extra-parens": 0,
    "no-extra-semi": 2,
    "no-fallthrough": 0,
    "no-floating-decimal": 0,
    "no-func-assign": 2,
    "no-implicit-coercion": 0,
    "no-implicit-globals": 2,
    "no-implied-eval": 2,
    "no-inline-comments": 2,
    "no-inner-declarations": [2, "both"],
    "no-invalid-regexp": 2,
    "no-invalid-this": 0,
    "no-irregular-whitespace": 2,
    "no-iterator": 2,
    "no-label-var": 2,
    "no-labels": 2,
    "no-lone-blocks": 2,
    "no-lonely-if": 1,
    "no-loop-func": 2,
    "no-mixed-requires": 2,
    "no-mixed-spaces-and-tabs": 2,
    "linebreak-style": [2, "unix"],
    "no-multi-spaces": 2,
    "no-multi-str": 1,
    "no-multiple-empty-lines": 2,
    "no-native-reassign": 2,
    "no-negated-condition": 0,
    "no-negated-in-lhs": 2,
    "no-nested-ternary": 2,
    "no-new": 2,
    "no-new-func": 2,
    "no-new-object": 2,
    "no-new-require": 2,
    "no-new-wrappers": 2,
    "no-obj-calls": 2,
    "no-octal": 2,
    "no-octal-escape": 2,
    "no-path-concat": 2,
    "no-plusplus": 0,
    "no-process-env": 1,
    "no-process-exit": 0,
    "no-proto": 2,
    "no-prototype-builtins": 0,
    "no-redeclare": 2,
    "no-regex-spaces": 2,
    "no-restricted-globals": 0,
    "no-restricted-modules": [2, "jquery", "underscore"],
    "no-restricted-syntax": 0,
    "no-return-assign": 2,
    "no-script-url": 2,
    "no-self-assign": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-shadow": 0,
    "no-shadow-restricted-names": 2,
    "no-whitespace-before-property": 2,
    "no-spaced-func": 2,
    "no-sparse-arrays": 2,
    "no-sync": 0,
    "no-ternary": 0,
    "no-trailing-spaces": 2,
    "no-throw-literal": 2,
    "no-undef": 2,
    "no-undef-init": 2,
    "no-undefined": 0,
    "no-unexpected-multiline": 2,
    "no-underscore-dangle": 0,
    "no-unmodified-loop-condition": 2,
    "no-unneeded-ternary": 2,
    "no-unreachable": 2,
    "no-unsafe-finally": 2,
    "no-unused-expressions": 2,
    "no-unused-labels": 2,
    "no-unused-vars": 2,
    "no-use-before-define": 0,
    "no-useless-call": 2,
    "no-useless-concat": 2,
    "no-useless-escape": 2,
    "no-void": 2,
    "no-warning-comments": 0,
    "no-with": 2,
    "no-magic-numbers": 0,
    "array-bracket-spacing": [2, "never"],
    "array-callback-return": 2,
    "accessor-pairs": 2,
    "block-scoped-var": 2,
    "block-spacing": [2, "always"],
    "brace-style": [2, "1tbs"],
    "callback-return": 0,
    "camelcase": 2,
    "comma-dangle": 0,
    "comma-spacing": [2, { "before": false, "after": true }],
    "comma-style": [2, "last"],
    "complexity": 0,
    "computed-property-spacing": [2, "never"],
    "consistent-return": 0,
    "consistent-this": [2, "self"],
    "curly": [2, "all"],
    "default-case": 0,
    "dot-location": [2, "property"],
    "dot-notation": 1,
    "eol-last": 2,
    "eqeqeq": [2, "smart"],
    "func-names": 0,
    "func-style": 0,
    "global-require": 0,
    "guard-for-in": 2,
    "handle-callback-err": 2,
    "id-length": 0,
    "indent": [2, 2, { "SwitchCase": 1 }],
    "init-declarations": 0,
    "key-spacing": [2, { "beforeColon": false, "afterColon": true, "mode": "strict" }],
    "keyword-spacing": 2,
    "lines-around-comment": 0,
    "max-depth": [1, 4],
    "max-len": 0,
    "max-nested-callbacks": [2, 4],
    "max-params": 0,
    "max-statements": 0,
    "max-statements-per-line": 0,
    "new-cap": 2,
    "new-parens": 2,
    "newline-after-var": 0,
    "newline-before-return": 0,
    "newline-per-chained-call": 0,
    "object-curly-newline": 0,
    "object-curly-spacing": [1, "always"],
    "object-property-newline": 0,
    "one-var": 0,
    "one-var-declaration-per-line": 0,
    "operator-assignment": 0,
    "operator-linebreak": [1, "before"],
    "padded-blocks": 0,
    "quote-props": 0,
    "quotes": [2, "single", "avoid-escape"],
    "radix": 2,
    "id-match": 0,
    "id-blacklist": 0,
    "require-jsdoc": 0,
    "semi": [2, "always"],
    "semi-spacing": 2,
    "sort-vars": 0,
    "space-before-blocks": [2, "always"],
    "space-before-function-paren": [2, { "anonymous": "always", "named": "never" }],
    "space-in-parens": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": 2,
    "spaced-comment": 0,
    "strict": [2, "global"],
    "unicode-bom": [2, "never"],
    "use-isnan": 2,
    "valid-jsdoc": 1,
    "valid-typeof": 2,
    "vars-on-top": 0,
    "wrap-iife": [2, "outside"],
    "wrap-regex": 2,
    "yoda": 2
  }
};
